// Generated by sprotodump. DO NOT EDIT!
// source: ..\..\Resource\RPCProtoSchema\ClusterServer.sproto

using System;
using Sproto;
using System.Collections.Generic;
using System.Collections.Concurrent;

namespace NetSprotoType { 
	public class ClusterServerSocketAccept : SprotoTypeBase {
		private static int max_field_count = 3;
		
		
		private Int64 _connection; // tag 0
		public Int64 connection {
			get { return _connection; }
			set { base.has_field.set_field (0, true); _connection = value; }
		}
		public bool HasConnection {
			get { return base.has_field.has_field (0); }
		}

		private string _ip; // tag 1
		public string ip {
			get { return _ip; }
			set { base.has_field.set_field (1, true); _ip = value; }
		}
		public bool HasIp {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _port; // tag 2
		public Int64 port {
			get { return _port; }
			set { base.has_field.set_field (2, true); _port = value; }
		}
		public bool HasPort {
			get { return base.has_field.has_field (2); }
		}

		public ClusterServerSocketAccept () : base(max_field_count) {}

		public ClusterServerSocketAccept (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.connection = base.deserialize.read_integer ();
					break;
				case 1:
					this.ip = base.deserialize.read_string ();
					break;
				case 2:
					this.port = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.connection, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_string (this.ip, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.port, 2);
			}

			return base.serialize.close ();
		}
	}


}

