// Generated by sprotodump. DO NOT EDIT!
using System;
using Sproto;
using System.Collections.Generic;
using System.Collections.Concurrent;

public class NetProtocol : ProtocolBase {
	private static NetProtocol Instance = null;
	
	public static NetProtocol GetInstance()
	{
		if (null == Instance)
		{
			Instance = new NetProtocol();
		}
		return Instance;
	}
	
	public int GetTag(string proto_name)
	{
		int tag = 0;
		ProtoNameDictionary.TryGetValue(proto_name, out tag);
		return tag;
	}
	
	private ConcurrentDictionary<string, int> ProtoNameDictionary;
	
  
	private NetProtocol() {
		ProtoNameDictionary = new ConcurrentDictionary<string, int>();
		

		ProtoNameDictionary.TryAdd("Error", Error.Tag);
		Protocol.SetProtocol<Error> (Error.Tag);
		Protocol.SetResponse<NetSprotoType.Error.response> (Error.Tag);

		ProtoNameDictionary.TryAdd("RPC", RPC.Tag);
		Protocol.SetProtocol<RPC> (RPC.Tag);
		Protocol.SetRequest<NetSprotoType.RPCParam> (RPC.Tag);
		Protocol.SetResponse<NetSprotoType.RPCParam> (RPC.Tag);

		ProtoNameDictionary.TryAdd("Timer", Timer.Tag);
		Protocol.SetProtocol<Timer> (Timer.Tag);

	}

	public class Error {
		public const int Tag = 102;
	}

	public class RPC {
		public const int Tag = 100;
	}

	public class Timer {
		public const int Tag = 101;
	}

}