// Generated by sprotodump. DO NOT EDIT!
// source: D:\Projects\SparkServer\spark-server\server\Test\RecvSkynetRequest\Resource\RPCProtoSchema\\SkynetMessageReceiver.sproto

using System;
using Sproto;
using System.Collections.Generic;
using System.Collections.Concurrent;

namespace NetSprotoType { 
	public class SkynetMessageReceiver_OnProcessRequest : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _request_count; // tag 0
		public Int64 request_count {
			get { return _request_count; }
			set { base.has_field.set_field (0, true); _request_count = value; }
		}
		public bool HasRequest_count {
			get { return base.has_field.has_field (0); }
		}

		private string _request_text; // tag 1
		public string request_text {
			get { return _request_text; }
			set { base.has_field.set_field (1, true); _request_text = value; }
		}
		public bool HasRequest_text {
			get { return base.has_field.has_field (1); }
		}

		public SkynetMessageReceiver_OnProcessRequest () : base(max_field_count) {}

		public SkynetMessageReceiver_OnProcessRequest (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.request_count = base.deserialize.read_integer ();
					break;
				case 1:
					this.request_text = base.deserialize.read_string ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.request_count, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_string (this.request_text, 1);
			}

			return base.serialize.close ();
		}
	}


	public class SkynetMessageReceiver_OnProcessRequestResponse : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _request_count; // tag 0
		public Int64 request_count {
			get { return _request_count; }
			set { base.has_field.set_field (0, true); _request_count = value; }
		}
		public bool HasRequest_count {
			get { return base.has_field.has_field (0); }
		}

		private string _request_text; // tag 1
		public string request_text {
			get { return _request_text; }
			set { base.has_field.set_field (1, true); _request_text = value; }
		}
		public bool HasRequest_text {
			get { return base.has_field.has_field (1); }
		}

		public SkynetMessageReceiver_OnProcessRequestResponse () : base(max_field_count) {}

		public SkynetMessageReceiver_OnProcessRequestResponse (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.request_count = base.deserialize.read_integer ();
					break;
				case 1:
					this.request_text = base.deserialize.read_string ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.request_count, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_string (this.request_text, 1);
			}

			return base.serialize.close ();
		}
	}


}

